# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf14e87223490fc0999f776613775ae10767d311dcc24dd159bb7cbe6fcf5d8891950d1c20f9216f888d6bf73bd8065dd85f8ae6b75efa1e75c88c237aac4093

test:
  secret_key_base: c22b8a6361af4d7e9800003190c09fd29fc9414b69e7ab1adc4f5e45a13ddc3336bcd278d22af41d38d84520b98f9d6a9c8e217adccd16259a2171bcd9a54df8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
